/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ikamobile.pa.thrift.server.acceptor;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-8-31")
public class OrderQuerySorterEnum implements org.apache.thrift.TBase<OrderQuerySorterEnum, OrderQuerySorterEnum._Fields>, java.io.Serializable, Cloneable, Comparable<OrderQuerySorterEnum> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OrderQuerySorterEnum");

  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField FLIGHT_DEP_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("flightDepTime", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField AREA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("areaId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new OrderQuerySorterEnumStandardSchemeFactory());
    schemes.put(TupleScheme.class, new OrderQuerySorterEnumTupleSchemeFactory());
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public com.ikamobile.pa.thrift.common.Sorter createTime; // required
  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public com.ikamobile.pa.thrift.common.Sorter flightDepTime; // required
  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public com.ikamobile.pa.thrift.common.Sorter areaId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see com.ikamobile.pa.thrift.common.Sorter
     */
    CREATE_TIME((short)1, "createTime"),
    /**
     * 
     * @see com.ikamobile.pa.thrift.common.Sorter
     */
    FLIGHT_DEP_TIME((short)2, "flightDepTime"),
    /**
     * 
     * @see com.ikamobile.pa.thrift.common.Sorter
     */
    AREA_ID((short)3, "areaId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CREATE_TIME
          return CREATE_TIME;
        case 2: // FLIGHT_DEP_TIME
          return FLIGHT_DEP_TIME;
        case 3: // AREA_ID
          return AREA_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.ikamobile.pa.thrift.common.Sorter.class)));
    tmpMap.put(_Fields.FLIGHT_DEP_TIME, new org.apache.thrift.meta_data.FieldMetaData("flightDepTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.ikamobile.pa.thrift.common.Sorter.class)));
    tmpMap.put(_Fields.AREA_ID, new org.apache.thrift.meta_data.FieldMetaData("areaId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, com.ikamobile.pa.thrift.common.Sorter.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OrderQuerySorterEnum.class, metaDataMap);
  }

  public OrderQuerySorterEnum() {
  }

  public OrderQuerySorterEnum(
    com.ikamobile.pa.thrift.common.Sorter createTime,
    com.ikamobile.pa.thrift.common.Sorter flightDepTime,
    com.ikamobile.pa.thrift.common.Sorter areaId)
  {
    this();
    this.createTime = createTime;
    this.flightDepTime = flightDepTime;
    this.areaId = areaId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OrderQuerySorterEnum(OrderQuerySorterEnum other) {
    if (other.isSetCreateTime()) {
      this.createTime = other.createTime;
    }
    if (other.isSetFlightDepTime()) {
      this.flightDepTime = other.flightDepTime;
    }
    if (other.isSetAreaId()) {
      this.areaId = other.areaId;
    }
  }

  public OrderQuerySorterEnum deepCopy() {
    return new OrderQuerySorterEnum(this);
  }

  @Override
  public void clear() {
    this.createTime = null;
    this.flightDepTime = null;
    this.areaId = null;
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public com.ikamobile.pa.thrift.common.Sorter getCreateTime() {
    return this.createTime;
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public OrderQuerySorterEnum setCreateTime(com.ikamobile.pa.thrift.common.Sorter createTime) {
    this.createTime = createTime;
    return this;
  }

  public void unsetCreateTime() {
    this.createTime = null;
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return this.createTime != null;
  }

  public void setCreateTimeIsSet(boolean value) {
    if (!value) {
      this.createTime = null;
    }
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public com.ikamobile.pa.thrift.common.Sorter getFlightDepTime() {
    return this.flightDepTime;
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public OrderQuerySorterEnum setFlightDepTime(com.ikamobile.pa.thrift.common.Sorter flightDepTime) {
    this.flightDepTime = flightDepTime;
    return this;
  }

  public void unsetFlightDepTime() {
    this.flightDepTime = null;
  }

  /** Returns true if field flightDepTime is set (has been assigned a value) and false otherwise */
  public boolean isSetFlightDepTime() {
    return this.flightDepTime != null;
  }

  public void setFlightDepTimeIsSet(boolean value) {
    if (!value) {
      this.flightDepTime = null;
    }
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public com.ikamobile.pa.thrift.common.Sorter getAreaId() {
    return this.areaId;
  }

  /**
   * 
   * @see com.ikamobile.pa.thrift.common.Sorter
   */
  public OrderQuerySorterEnum setAreaId(com.ikamobile.pa.thrift.common.Sorter areaId) {
    this.areaId = areaId;
    return this;
  }

  public void unsetAreaId() {
    this.areaId = null;
  }

  /** Returns true if field areaId is set (has been assigned a value) and false otherwise */
  public boolean isSetAreaId() {
    return this.areaId != null;
  }

  public void setAreaIdIsSet(boolean value) {
    if (!value) {
      this.areaId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((com.ikamobile.pa.thrift.common.Sorter)value);
      }
      break;

    case FLIGHT_DEP_TIME:
      if (value == null) {
        unsetFlightDepTime();
      } else {
        setFlightDepTime((com.ikamobile.pa.thrift.common.Sorter)value);
      }
      break;

    case AREA_ID:
      if (value == null) {
        unsetAreaId();
      } else {
        setAreaId((com.ikamobile.pa.thrift.common.Sorter)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CREATE_TIME:
      return getCreateTime();

    case FLIGHT_DEP_TIME:
      return getFlightDepTime();

    case AREA_ID:
      return getAreaId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CREATE_TIME:
      return isSetCreateTime();
    case FLIGHT_DEP_TIME:
      return isSetFlightDepTime();
    case AREA_ID:
      return isSetAreaId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof OrderQuerySorterEnum)
      return this.equals((OrderQuerySorterEnum)that);
    return false;
  }

  public boolean equals(OrderQuerySorterEnum that) {
    if (that == null)
      return false;

    boolean this_present_createTime = true && this.isSetCreateTime();
    boolean that_present_createTime = true && that.isSetCreateTime();
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (!this.createTime.equals(that.createTime))
        return false;
    }

    boolean this_present_flightDepTime = true && this.isSetFlightDepTime();
    boolean that_present_flightDepTime = true && that.isSetFlightDepTime();
    if (this_present_flightDepTime || that_present_flightDepTime) {
      if (!(this_present_flightDepTime && that_present_flightDepTime))
        return false;
      if (!this.flightDepTime.equals(that.flightDepTime))
        return false;
    }

    boolean this_present_areaId = true && this.isSetAreaId();
    boolean that_present_areaId = true && that.isSetAreaId();
    if (this_present_areaId || that_present_areaId) {
      if (!(this_present_areaId && that_present_areaId))
        return false;
      if (!this.areaId.equals(that.areaId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_createTime = true && (isSetCreateTime());
    list.add(present_createTime);
    if (present_createTime)
      list.add(createTime.getValue());

    boolean present_flightDepTime = true && (isSetFlightDepTime());
    list.add(present_flightDepTime);
    if (present_flightDepTime)
      list.add(flightDepTime.getValue());

    boolean present_areaId = true && (isSetAreaId());
    list.add(present_areaId);
    if (present_areaId)
      list.add(areaId.getValue());

    return list.hashCode();
  }

  @Override
  public int compareTo(OrderQuerySorterEnum other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCreateTime()).compareTo(other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFlightDepTime()).compareTo(other.isSetFlightDepTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFlightDepTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.flightDepTime, other.flightDepTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAreaId()).compareTo(other.isSetAreaId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAreaId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.areaId, other.areaId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("OrderQuerySorterEnum(");
    boolean first = true;

    sb.append("createTime:");
    if (this.createTime == null) {
      sb.append("null");
    } else {
      sb.append(this.createTime);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("flightDepTime:");
    if (this.flightDepTime == null) {
      sb.append("null");
    } else {
      sb.append(this.flightDepTime);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("areaId:");
    if (this.areaId == null) {
      sb.append("null");
    } else {
      sb.append(this.areaId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OrderQuerySorterEnumStandardSchemeFactory implements SchemeFactory {
    public OrderQuerySorterEnumStandardScheme getScheme() {
      return new OrderQuerySorterEnumStandardScheme();
    }
  }

  private static class OrderQuerySorterEnumStandardScheme extends StandardScheme<OrderQuerySorterEnum> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OrderQuerySorterEnum struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.createTime = com.ikamobile.pa.thrift.common.Sorter.findByValue(iprot.readI32());
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FLIGHT_DEP_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.flightDepTime = com.ikamobile.pa.thrift.common.Sorter.findByValue(iprot.readI32());
              struct.setFlightDepTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // AREA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.areaId = com.ikamobile.pa.thrift.common.Sorter.findByValue(iprot.readI32());
              struct.setAreaIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OrderQuerySorterEnum struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.createTime != null) {
        oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
        oprot.writeI32(struct.createTime.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.flightDepTime != null) {
        oprot.writeFieldBegin(FLIGHT_DEP_TIME_FIELD_DESC);
        oprot.writeI32(struct.flightDepTime.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.areaId != null) {
        oprot.writeFieldBegin(AREA_ID_FIELD_DESC);
        oprot.writeI32(struct.areaId.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OrderQuerySorterEnumTupleSchemeFactory implements SchemeFactory {
    public OrderQuerySorterEnumTupleScheme getScheme() {
      return new OrderQuerySorterEnumTupleScheme();
    }
  }

  private static class OrderQuerySorterEnumTupleScheme extends TupleScheme<OrderQuerySorterEnum> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OrderQuerySorterEnum struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCreateTime()) {
        optionals.set(0);
      }
      if (struct.isSetFlightDepTime()) {
        optionals.set(1);
      }
      if (struct.isSetAreaId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCreateTime()) {
        oprot.writeI32(struct.createTime.getValue());
      }
      if (struct.isSetFlightDepTime()) {
        oprot.writeI32(struct.flightDepTime.getValue());
      }
      if (struct.isSetAreaId()) {
        oprot.writeI32(struct.areaId.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OrderQuerySorterEnum struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.createTime = com.ikamobile.pa.thrift.common.Sorter.findByValue(iprot.readI32());
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.flightDepTime = com.ikamobile.pa.thrift.common.Sorter.findByValue(iprot.readI32());
        struct.setFlightDepTimeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.areaId = com.ikamobile.pa.thrift.common.Sorter.findByValue(iprot.readI32());
        struct.setAreaIdIsSet(true);
      }
    }
  }

}

